services:
  web:
    image: node:20-alpine
    container_name: cvcwebsolutions-app
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run build && npm start"
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.production
    volumes:
      # Mount code as volume so restarts pick up changes
      - .:/app
      # Persist node_modules
      - /app/node_modules
      # Persist build
      - /app/.next
      # Persist database
      - ./data:/app/data
      # Persist uploaded media
      - ./public/media:/app/public/media
      - ./public/screenshots:/app/public/screenshots
      - ./public/portfolio:/app/public/portfolio
    networks:
      - cvc-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  cvc-network:
    driver: bridge
