name: Deploy to Production

on:
  push:
    branches:
      - master  # Triggers on push to master branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            set -e  # Exit on any error

            cd /home/ploi/cvcwebsolutions

            # Stash any local changes and pull latest
            echo "📥 Pulling latest code from GitHub..."
            git stash --include-untracked || true
            git pull origin master || { echo "❌ Git pull failed"; exit 1; }

            # Ensure .env.production exists
            if [ ! -f .env.production ]; then
              echo "⚠️ .env.production missing! Deployment cannot continue."
              exit 1
            fi

            # Build new image first (before stopping old container for zero downtime)
            echo "🔨 Building new Docker image..."
            docker compose -f docker-compose.prod.yml build || { echo "❌ Build failed"; exit 1; }

            # Quick restart with new image
            echo "🔄 Restarting with new image..."
            docker compose -f docker-compose.prod.yml up -d --force-recreate || { echo "❌ Container start failed"; exit 1; }

            # Wait for container to be healthy
            echo "⏳ Waiting for container to be ready..."
            sleep 10

            # Verify container is running
            if ! docker compose -f docker-compose.prod.yml ps | grep -q "Up"; then
              echo "❌ Container failed to start!"
              docker compose -f docker-compose.prod.yml logs --tail=50
              exit 1
            fi

            # Clean up old images
            echo "🧹 Cleaning up old Docker images..."
            docker image prune -f || true

            # Show final status
            echo "✅ Deployment complete!"
            docker compose -f docker-compose.prod.yml ps

            echo "📋 Recent logs:"
            docker compose -f docker-compose.prod.yml logs --tail=30

      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Successfully deployed to production!"
          echo "🌐 Site: https://cvcwebsolutions.com"

      - name: Deployment failed
        if: failure()
        run: |
          echo "❌ Deployment failed! Check the logs above."
